# Generated by Django 4.0.3 on 2022-04-16 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('scopus_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='knowledge.affiliation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scopus_id', models.IntegerField(unique=True)),
                ('ciencia_id', models.CharField(max_length=100, unique=True)),
                ('orcid_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('name_list', models.TextField(null=True)),
                ('citation_count', models.IntegerField(default=0)),
                ('cited_by_count', models.IntegerField(default=0)),
                ('bio', models.TextField(null=True)),
                ('degrees', models.TextField(null=True)),
                ('distinctions', models.TextField(null=True)),
                ('current_affiliations', models.ManyToManyField(related_name='Current', to='knowledge.affiliation')),
                ('domains', models.ManyToManyField(to='knowledge.area')),
                ('previous_affiliations', models.ManyToManyField(related_name='Previous', to='knowledge.affiliation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scopus_id', models.IntegerField(null=True)),
                ('ciencia_id', models.CharField(max_length=100, null=True)),
                ('doi', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('keywords', models.TextField(null=True)),
                ('available', models.BooleanField()),
                ('clean_text', models.TextField(null=True)),
                ('abstract', models.TextField(null=True)),
                ('areas', models.ManyToManyField(to='knowledge.area')),
                ('authors', models.ManyToManyField(to='knowledge.author')),
                ('publication_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.publicationtype')),
            ],
            options={
                'ordering': ['date', 'title'],
                'unique_together': {('scopus_id', 'ciencia_id')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('desc', models.TextField(null=True)),
                ('date', models.DateField()),
                ('areas', models.ManyToManyField(to='knowledge.area')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='author',
            name='projects',
            field=models.ManyToManyField(to='knowledge.project'),
        ),
        migrations.AddField(
            model_name='author',
            name='publications',
            field=models.ManyToManyField(to='knowledge.publication'),
        ),
    ]
