# Generated by Django 4.0.3 on 2022-04-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='ciencia_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='orcid_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='scopus_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
