# Generated by Django 4.0.3 on 2022-04-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_alter_author_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='ciencia_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='orcid_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='scopus_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='ciencia_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='scopus_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('scopus_id', 'orcid_id'), ('scopus_id', 'ciencia_id', 'orcid_id'), ('scopus_id', 'ciencia_id'), ('ciencia_id', 'orcid_id')},
        ),
        migrations.AlterUniqueTogether(
            name='publication',
            unique_together={('scopus_id', 'ciencia_id')},
        ),
    ]
