# Generated by Django 4.0.3 on 2022-04-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_alter_author_ciencia_id_alter_author_orcid_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date', 'name']},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-date', 'title']},
        ),
        migrations.AlterModelOptions(
            name='publicationtype',
            options={'ordering': ['name']},
        ),
    ]
