# Generated by Django 4.0.3 on 2022-05-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_alter_author_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('scopus_id', 'ciencia_id', 'orcid_id')},
        ),
    ]
