# Generated by Django 4.0.3 on 2022-05-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_alter_author_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='scopus_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
