# Generated by Django 4.0.3 on 2022-05-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0008_author_synced_ciencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='ciencia_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='current_affiliations',
            field=models.ManyToManyField(blank=True, related_name='Current', to='knowledge.affiliation'),
        ),
        migrations.AlterField(
            model_name='author',
            name='degrees',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='distinctions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='domains',
            field=models.ManyToManyField(blank=True, to='knowledge.area'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='name_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='orcid_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='previous_affiliations',
            field=models.ManyToManyField(blank=True, related_name='Previous', to='knowledge.affiliation'),
        ),
        migrations.AlterField(
            model_name='author',
            name='projects',
            field=models.ManyToManyField(blank=True, to='knowledge.project'),
        ),
        migrations.AlterField(
            model_name='author',
            name='publications',
            field=models.ManyToManyField(blank=True, to='knowledge.publication'),
        ),
        migrations.AlterField(
            model_name='author',
            name='scopus_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
