# Generated by Django 4.0.3 on 2022-05-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0009_alter_author_options_alter_author_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='ciencia_id',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='degrees',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='author',
            name='distinctions',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='name_list',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='author',
            name='orcid_id',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
