# Generated by Django 4.0.3 on 2022-05-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0010_alter_author_bio_alter_author_ciencia_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
