# Generated by Django 4.0.3 on 2022-05-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0011_alter_affiliation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='h_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
