# Generated by Django 4.0.3 on 2022-05-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0014_remove_publication_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='keywords',
            field=models.TextField(default='[]'),
        ),
    ]
