# Generated by Django 4.0.3 on 2022-05-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0015_alter_publication_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['-code']},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='publication',
            name='keywords',
        ),
        migrations.AddField(
            model_name='publication',
            name='keywords',
            field=models.ManyToManyField(to='knowledge.keyword'),
        ),
    ]
