# Generated by Django 4.0.3 on 2022-05-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0016_keyword_alter_area_options_alter_author_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['name']},
        ),
    ]
