# Generated by Django 4.0.3 on 2022-06-12 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0019_publication_possible_duplicates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='possible_duplicates',
        ),
    ]
